FROM apache/airflow:2.7.3-python3.11

USER root
RUN apt-get update && apt-get install -y git && apt-get clean

USER airflow

# Install Python dependencies
RUN pip install --no-cache-dir \
    pandas==2.0.3 \
    numpy==1.24.3 \
    scikit-learn==1.3.0 \
    mlflow==2.18.0 \
    boto3==1.34.51 \
    requests==2.31.0 \
    ydata-profiling==4.10.0 \
    psycopg2-binary==2.9.9 \
    joblib==1.3.2